version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_VERSION=1.0.0
      - ENV=development
    volumes:
      - ./app:/app
    restart: unless-stopped

  test:
    build: .
    command: pytest test_app.py -v
    environment:
      - ENV=testing
    volumes:
      - ./app:/app